### PR TITLE
Add Celery backend

### PR DESCRIPTION
**Pull request by candleindark**
Configure Celery to have a backend. This PR resolves https://github.com/datalad/datalad-registry/issues/86.

### CODE REVIEW

**Comment by candleindark** [comment]
The current state of this PR should have added a backend to the Celery service correctly. However, the tests for the project need to be adjusted. The test GitHub Action may also need to be adjusted as well for testing now requires a running Redis service.

The current state, with a backend set up, should be useful in resolving https://github.com/datalad/datalad-registry/issues/93.

**Comment by yarikoptic** [comment]
oh, so current run on typhon is working ok without celery backend?

**Comment by candleindark** [comment]
> oh, so current run on typhon is working ok without celery backend?

The backend service is running in Typhon but not utilized.

The tests need to be updated before I can merge this code.

**Comment by candleindark** [comment]
Frankly, I want to rewrite some of the code that set up the Flask app and Celery app. Those code currently are really messy. Rewriting those code will also re-attach the backend but possibly in a even more uniform way, along with other configurations.

**Comment by yarikoptic** [comment]
do we still need this PR in the long run?

**Comment by candleindark** [comment]
This solution has been incorporated into #222. Thus, this PR should be closed.

**Pull request closed without merging**
